### PR TITLE
Refactor Watson sentiment analysis

### LINKED ISSUE #8: Refactor Watson tone analysis

### PR DESCRIPTION
**Pull request by Autumn-Martin**
** IN PROGRESS ** 
- [ ] Wrote Tests
- [X] Implemented
- [X] Reviewed

## Necessary checkmarks

- [ ] All Tests are Passing

- [X] The code will run locally

## Type of change

- [X] New feature
- [ ] Bug Fix

### Implements
Refactors prior work on retrieving tweets, cleaning them, and running Watson sentiment analysis. Extracts methods out of views.py and makes the request to `/teller/watson_analysis` dynamic for different coins. 

## Check the correct boxes

- [X] This broke nothing
- [ ] This broke some stuff
- [ ] This broke everything

## Testing Changes

- [X] No Tests have been changed
- [ ] Some Tests have been changed
- [ ] All of the Tests have been changed(Please describe what in the world happened)

## Checklist

- [X] My code has no commented out code (explanatory comments are fine)
- [X] I have reviewed my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have fully tested my code

### CODE REVIEW

**Comment by Autumn-Martin** [comment]
Good to know! Thanks, I'll adjust the order.

**Comment by Autumn-Martin** [comment]
@patrickshobe Is this order what you were thinking? I based it off of a mix of PEP8, isort, and your advice. 
screen shot 2019-01-01 at 12 33 48 pm

**Comment by DanielMulitauopele** [comment]
The refactoring looks really good. Good job!

**Comment by Autumn-Martin** [comment]
Thanks Daniel!

**Pull request merged**
